USE SCHEMA yesql_sales.curated;

CREATE VIEW customer_monthly_sales_2019_view (CUSTOMERID, FIRSTNAME, LASTNAME, MONTH, TOTAL_AMOUNT_PURCHASED) AS
SELECT SALES.CUSTOMERID, CUSTOMERS.FIRSTNAME, CUSTOMERS.LASTNAME, month(DATE), SUM(PRODUCTS.PRICE * SALES.QUANTITY)
FROM SALES
JOIN CUSTOMERS ON SALES.CUSTOMERID=CUSTOMERS.CUSTOMERID
JOIN PRODUCTS ON SALES.PRODUCTID = PRODUCTS.PRODUCTID
WHERE year(DATE)=2019
GROUP BY SALES.CUSTOMERID, CUSTOMERS.FIRSTNAME, CUSTOMERS.LASTNAME, month(DATE)
ORDER BY month(DATE);



CREATE VIEW top_ten_customers_amount_view (CUSTOMERID, FIRSTNAME, LASTNAME, TOTAL_LIFETIME_AMOUNT_PURCHASED) AS
SELECT TOP 10 SALES.CUSTOMERID, CUSTOMERS.FIRSTNAME, CUSTOMERS.LASTNAME, SUM(PRODUCTS.PRICE * SALES.QUANTITY)
FROM SALES
JOIN CUSTOMERS ON SALES.CUSTOMERID=CUSTOMERS.CUSTOMERID
JOIN PRODUCTS ON SALES.PRODUCTID = PRODUCTS.PRODUCTID
GROUP BY SALES.CUSTOMERID, CUSTOMERS.FIRSTNAME, CUSTOMERS.LASTNAME
ORDER BY SUM(PRODUCTS.PRICE * SALES.QUANTITY) DESC;



CREATE VIEW product_sales_view (ORDERID, EMPLOYEEID, CUSTOMERID, PRODUCTID, NAME, PRICE, QUANTITY, TOTAL_SALE_AMOUNT, DATE, YEAR, MONTH) AS
SELECT SALES.ORDERID, SALES.EMPLOYEEID, SALES.CUSTOMERID, SALES.PRODUCTID, PRODUCTS.NAME, PRODUCTS.PRICE, SALES.QUANTITY, PRODUCTS.PRICE * SALES.QUANTITY, SALES.DATE, YEAR(SALES.DATE), MONTH(SALES.DATE)
FROM SALES
JOIN PRODUCTS ON SALES.PRODUCTID = PRODUCTS.PRODUCTID;
